{% set name = "fluidfft" %}
{% set version = "0.4.0" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5fd2058c8ddd7934339a0ccbf98df4a8b43de716e0dcc770d1b2cb09e72be64

build:
  number: {{ build }}
  skip: true  # [py<39]
  entry_points:
    - fluidfft-bench = fluidfft.bench:run
    - fluidfft-bench-analysis = fluidfft.bench_analysis:run

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - meson-python
    - numpy
    - transonic >=0.6.1
    - pythran >=0.9.7
    # pythran code needs clang-cl on windows
    - clang  # [win]
  run:
    - python
    - fluiddyn
    - pandas
    - transonic >=0.6.1
    - pyfftw

test:
  imports:
    - fluidfft
    - fluidfft.bench
    - fluidfft.bench_analysis
    - fluidfft.fft2d
    - fluidfft.fft3d
    - fluidfft.util
  commands:
    - fluidfft-bench -h
    - fluidfft-bench-analysis -h
    - fluidfft-bench 32 -d 3

about:
  home: https://foss.heptapod.net/fluiddyn/fluidfft
  license: LicenseRef-CeCILL
  license_file: LICENSE.txt
  summary: Efficient and easy Fast Fourier Transform (FFT) for Python.
  description: |
    Fluidfft provides C++ classes and their Python wrapper classes written in
    Cython useful to perform Fast Fourier Transform (FFT) with different
    libraries
  doc_url: https://fluidfft.readthedocs.io

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
