{% set name = "fluidfft" %}
{% set version = "0.4.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c56278daf30a8d3af2ef872da7246ba64d75f1f902651308edc54e880a134b5

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - fluidfft-bench = fluidfft.bench:run
    - fluidfft-bench-analysis = fluidfft.bench_analysis:run

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - meson-python
    - numpy
    - transonic >=0.6.4
    - pythran >=0.9.7
    # pythran code needs clang-cl on windows
    - clang  # [win]
  run:
    - python
    - fluiddyn
    - pandas
    - transonic >=0.6.4
    - pyfftw
    - importlib_metadata  # [py<310]

test:
  imports:
    - fluidfft
    - fluidfft.bench
    - fluidfft.bench_analysis
    - fluidfft.fft2d.operators
    - fluidfft.fft3d.operators
    - fluidfft.util
  commands:
    - fluidfft-bench -h
    - fluidfft-bench-analysis -h
    - fluidfft-bench 32 -d 3

about:
  home: https://foss.heptapod.net/fluiddyn/fluidfft
  license: LicenseRef-CeCILL
  license_file: LICENSE.txt
  summary: Efficient and easy Fast Fourier Transform (FFT) for Python.
  description: |
    Fluidfft provides C++ classes and their Python wrapper classes written in
    Cython useful to perform Fast Fourier Transform (FFT) with different
    libraries
  doc_url: https://fluidfft.readthedocs.io

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
