{% set name = "fluidfft" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31635a6fe22279c1c47bbf3a61202ab36c6110be409e5c7a785ef8a17158e1df

build:
  number: 0
  skip: true  # [py<310]
  entry_points:
    - fluidfft-bench = fluidfft.bench:run
    - fluidfft-bench-analysis = fluidfft.bench_analysis:run

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - ninja                                  # [unix]
    - pkg-config                             # [unix]
    # pythran code needs clang-cl on windows
    - clang                                  # [win]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - python-build
    - pip
    - meson-python
    - numpy
    - transonic >=0.6.4
    - pythran >=0.9.7
  run:
    - python
    - fluiddyn
    - pandas
    - transonic >=0.6.4
    - pyfftw
    - importlib-metadata  # [py<310]

test:
  imports:
    # manual imports of Pythran extensions
    - fluidfft.fft2d.__pythran__.operators
    - fluidfft.fft3d.__pythran__.operators
    - fluidfft
    - fluidfft.bench
    - fluidfft.bench_analysis
    - fluidfft.fft2d.operators
    - fluidfft.fft3d.operators
    - fluidfft.util
  commands:
    - fluidfft-bench -h
    - fluidfft-bench-analysis -h
    - fluidfft-bench 32 -d 3

about:
  home: https://foss.heptapod.net/fluiddyn/fluidfft
  license: LicenseRef-CeCILL
  license_file: LICENSE.txt
  summary: Efficient and easy Fast Fourier Transform (FFT) for Python.
  description: |
    Fluidfft provides C++ classes and their Python wrapper classes written in
    Cython useful to perform Fast Fourier Transform (FFT) with different
    libraries
  doc_url: https://fluidfft.readthedocs.io

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
